In [3]:
#Exceptions (İstisnalar) - try, except, else, finally

try:
    fh = open("mytestfile0102", "w")
    fh.write("This is my test file for exceptions")

except IOError:
    print("Error: cannot find file or read data")
    
else:
    print("Content was written to the file successfully")

Content was written to the file successfully


In [2]:
try:
    fh = open("mytestfile2023", "w")
    fh.write("This is my test file for exceptions")
    
finally:
    print("Error : cannot find file or read data")

Error : cannot find file or read data


In [4]:
#delete
mylist = ['python', 'java', 2017, 2023]
print(mylist)
del mylist[1]
print("After deleting value at index 1 : ", mylist)

['python', 'java', 2017, 2023]
After deleting value at index 1 :  ['python', 2017, 2023]


In [5]:
#update
lst2 = ['python', 'geometry', 2017, 2023]
print("Value available at index 3 :", lst2[3])
lst2[3] = 5000
print("New value available at index 3 :", lst2[3])

Value available at index 3 : 2023
New value available at index 3 : 5000


In [6]:
txt = "but soft what light in window breaks"
words = txt.split()
print(words)

['but', 'soft', 'what', 'light', 'in', 'window', 'breaks']


In [7]:
pow2 = [2 ** x for x in range(10) if x > 5]
print(pow2)

[64, 128, 256, 512]


In [8]:
pow2 = []
for x in range(10):
    pow2.append(print(2**x))

1
2
4
8
16
32
64
128
256
512


In [9]:
langs = []
langs.append("Python")
langs.append("Perl")
print(langs)

['Python', 'Perl']


In [10]:
#insert
langs.insert(0, "PHP")
langs.insert(2, "Ada")
print(langs)

['PHP', 'Python', 'Ada', 'Perl']


In [11]:
#extend
langs.extend(("Javascript", "Actionscript"))
print(langs)

['PHP', 'Python', 'Ada', 'Perl', 'Javascript', 'Actionscript']


In [12]:
del langs[1]
print(langs)

['PHP', 'Ada', 'Perl', 'Javascript', 'Actionscript']


In [13]:
del langs[:]

In [14]:
print(langs)

[]


In [15]:
#dictionary
mydict = {'Name' : 'Fırat', 'Age' : 50, 'Class' : 'Master'}
print("mydict['Name']: ", mydict['Name'])
print("mydict['Age']: ", mydict['Age'])

mydict['Name']:  Fırat
mydict['Age']:  50


In [16]:
mydict = {'Name' : 'Fırat', 'Age' : 50, 'Class' : 'Master'}
mydict['Age'] = 30
mydict['School'] = 'University'
print("mydict['School']: ", mydict['School'])
print("mydict['Age']: ", mydict['Age'])

mydict['School']:  University
mydict['Age']:  30


In [17]:
mydict = {'Name' : 'Fırat', 'Age' : 50, 'Class' : 'Master', 'Name' : 'Şahin'}
print("mydict['Name']: ", mydict['Name'])

mydict['Name']:  Şahin


In [18]:
mydict = {'Name' : 'Fırat', 'Age' : 50, 'Class' : 'Master'}
del mydict['Name']

In [19]:
mydict.clear()

In [20]:
del mydict

In [21]:
print("mydict['School']: ", mydict['School'])
print("mydict['Age']: ", mydict['Age'])

NameError: name 'mydict' is not defined

In [22]:
#get, item metodları
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222'}
value = phonebook.get('Katie')
print(value)

555-2222


In [24]:
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222', 'Joanne' : '555-3333'}
for key, value in phonebook.items():
    print(key, value, sep = ':')

Chris:555-1111
Katie:555-2222
Joanne:555-3333


In [33]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import time

In [38]:
from numpy import *
import time
def trad_version ():
    t1 = time . time ()
    X = range (10000000)
    Y = range (10000000)
    Z = []
    for i in range (len (X)):
        Z. append (X[i] + Y[i])
    return time . time () - t1

In [39]:
trad_version()

5.594812870025635

In [40]:
def numpy_version():
    t1 = time.time()
    X = arange(10000000)
    Y = arange(10000000)
    Z = X + Y
    return time.time() - t1

In [41]:
numpy_version()

0.054592132568359375

In [42]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [43]:
type(list1)

list

In [44]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [45]:
arr1.data

In [46]:
type(arr1)

numpy.ndarray

In [47]:
arr1.dtype

dtype('int32')

In [48]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [49]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [52]:
arr3 = np.arange(0,10)
arr3.shape

(10,)

In [53]:
arr3.size

10

In [54]:
arr3.dtype

dtype('int32')

In [55]:
arr3.nbytes

40

In [56]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [59]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [60]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [61]:
ar1 = np.arange(1,20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [62]:
ar1 = np.arange(1,20)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [64]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [66]:
np.random.random(4).round(2)

array([0.32, 0.93, 0.84, 0.55])

In [67]:
np.random.randint(0, 500, 5)

array([ 86, 436, 367, 260, 487])

In [68]:
np.random.randint(100, 1000, 8)

array([621, 276, 126, 743, 350, 949, 893, 972])

In [69]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [70]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [71]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [72]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [73]:
f1 = np.random.uniform(5, 10, size=(10))
f1

array([6.96058759, 6.71589008, 8.64524854, 7.19286122, 5.29838948,
       6.99022128, 8.68997703, 5.91245865, 5.87725878, 7.65775687])

In [74]:
np.floor(f1)

array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [75]:
np.trunc(f1)

array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [76]:
f1.astype(int)

array([6, 6, 8, 7, 5, 6, 8, 5, 5, 7])

In [77]:
b2 = np.random.randn(10)
b2

array([ 2.20742744,  0.52274247,  0.46564476,  0.72491523,  1.49582653,
        0.74658059, -1.10098526, -1.4103012 , -0.74765132, -0.98486761])

In [78]:
arr1

array([10, 20, 30, 40, 50, 60])

In [79]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [80]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [81]:
arr2.sum()

190

In [82]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [83]:
#min(), max(), argmin(), argmax()

In [84]:
arr2.mean()

10.0

In [85]:
np.median(arr2)

10.0

In [86]:
np.var(arr2)

30.0

In [87]:
np.std(arr2)

5.477225575051661

In [89]:
A = np.array([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [90]:
A.sum()

129

In [91]:
A.max()

22

In [92]:
A.min()

0

In [93]:
np.amin(A, axis = 0)

array([1, 2, 1, 0])

In [94]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [95]:
A.mean()

8.0625

In [96]:
np.mean(A)

8.0625

In [97]:
np.median(A)

6.5

In [98]:
np.var(A)

40.30859375

In [99]:
np.std(A)

6.348904925260734

In [100]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3
