In [2]:
import numpy as np
#Printing Options, set_printoptions
np.set_printoptions(precision = 4)
a = np.array([12.654398765, 90.7864098354674])
a

array([12.6544, 90.7864])

In [3]:
np.set_printoptions(precision = 2)
a = np.array([12.654398765, 90.7864098354674])
a

array([12.65, 90.79])

In [4]:
np.set_printoptions(threshold = 3)
np.arange(200)

array([  0,   1,   2, ..., 197, 198, 199])

In [5]:
np.arange(0, 121).reshape(11, -1)

array([[  0,   1,   2, ...,   8,   9,  10],
       [ 11,  12,  13, ...,  19,  20,  21],
       [ 22,  23,  24, ...,  30,  31,  32],
       ...,
       [ 88,  89,  90, ...,  96,  97,  98],
       [ 99, 100, 101, ..., 107, 108, 109],
       [110, 111, 112, ..., 118, 119, 120]])

In [6]:
np.arange(1, 1100)

array([   1,    2,    3, ..., 1097, 1098, 1099])

In [7]:
#Vektör Toplama

In [8]:
v1 = np.array([1,2])
v2 = np.array([3,4])
v3 = v1 + v2
#OR
v3 = np.add(v1, v2)
print("V3 =", v3)

V3 = [4 6]


In [9]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

dotp = a1@a2
print("Dot product - ", dotp)

dotp = np.dot(a1, a2)
print("Dot product using np.dot - ", dotp)

dotp = np.inner(a1, a2)
print("Dot product using np.inner - ", dotp)

dotp = sum(np.multiply(a1, a2))
print("Dot product using sum & np.multiply - ", dotp)

dotp = np.matmul(a1, a2)
print("Dot product using np.matmul - ", dotp)

dotp = 0
for i in range(len(a1)):
    dotp = dotp + a1[i]*a2[i]
print("Dot product using for loop - ", dotp)

Dot product -  32
Dot product using np.dot -  32
Dot product using np.inner -  32
Dot product using sum & np.multiply -  32
Dot product using np.matmul -  32
Dot product using for loop -  32


In [10]:
#Vektörün Uzunluğu (Length)
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.dot(v3, v3))
length

9.539392014169456

In [12]:
length2 = np.sqrt(sum(np.multiply(v3, v3)))
length2

9.539392014169456

In [13]:
length3 = np.sqrt(np.matmul(v3, v3))
length3

9.539392014169456

In [14]:
#Normalizasyon
v1 = [2,3]
length_v1 = np.sqrt(np.dot(v1, v1))
norm_v1 = v1 / length_v1
length_v1, norm_v1

(3.605551275463989, array([0.55, 0.83]))

In [15]:
v1 = [2,3]
norm_v1 = v1 / np.linalg.norm(v1)
norm_v1

array([0.55, 0.83])

In [19]:
#Matris işlemleri
np.set_printoptions(precision = 8, suppress = False, threshold = 1000, formatter = None)
mat1 = np.random.randint(0, 1000, 100).reshape(10, 10)
mat1

array([[308, 370, 822, 838, 763, 913, 111, 239, 870, 899],
       [178, 329, 805, 829, 866, 889,  73, 878, 678, 776],
       [745, 485, 937,  24, 891, 571, 454, 933, 925, 679],
       [325, 808, 755, 706, 290, 945,  29, 758, 358, 509],
       [ 21, 198,  50, 104, 427, 320,  99,  86, 436, 413],
       [234, 440, 725, 901, 819, 153, 577, 139, 222, 447],
       [185, 375, 344, 261, 238, 177, 643, 501, 319, 680],
       [173, 173, 750, 949,  17, 624, 915, 482, 872,  42],
       [950, 530, 979, 688, 586,  94, 310,  22, 920, 326],
       [995, 282, 468, 763, 886, 782, 503,  76, 682, 360]])

In [20]:
mat1[0, 0]

308

In [21]:
mat1[mat1 > 500]

array([822, 838, 763, 913, 870, 899, 805, 829, 866, 889, 878, 678, 776,
       745, 937, 891, 571, 933, 925, 679, 808, 755, 706, 945, 758, 509,
       725, 901, 819, 577, 643, 501, 680, 750, 949, 624, 915, 872, 950,
       530, 979, 688, 586, 920, 995, 763, 886, 782, 503, 682])

In [22]:
#Birim (Identity) Matrix
I = np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [23]:
D = np.diag([1,2,3,4,5,6,7,8,9])
D

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [24]:
#Üçgen (Triangular) Matris
#tril, triu
M = np.random.randn(5,5)
U = np.triu(M)
L = np.tril(M)
print(M)
print('\n')
print(U)
print('\n')
print(L)

[[-1.13518586 -2.18509024 -0.98277606 -0.12239913 -0.62292775]
 [ 1.4503227   0.32659445  0.13664652 -2.97807788  1.1153162 ]
 [-1.24808155 -1.634623   -0.5748619   0.7780144   0.77887918]
 [-1.1638623   1.71616266  0.87910879 -0.29114081 -1.68389576]
 [ 0.37585704  1.28329762 -1.19537538  0.50994944 -0.95529377]]


[[-1.13518586 -2.18509024 -0.98277606 -0.12239913 -0.62292775]
 [ 0.          0.32659445  0.13664652 -2.97807788  1.1153162 ]
 [ 0.          0.         -0.5748619   0.7780144   0.77887918]
 [ 0.          0.          0.         -0.29114081 -1.68389576]
 [ 0.          0.          0.          0.         -0.95529377]]


[[-1.13518586  0.          0.          0.          0.        ]
 [ 1.4503227   0.32659445  0.          0.          0.        ]
 [-1.24808155 -1.634623   -0.5748619   0.          0.        ]
 [-1.1638623   1.71616266  0.87910879 -0.29114081  0.        ]
 [ 0.37585704  1.28329762 -1.19537538  0.50994944 -0.95529377]]


In [25]:
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [27]:
A.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [28]:
#Satır/Sütun Swap İşlemleri

In [30]:
m1 = np.arange(0, 16).reshape(4,-1)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
m1[[0, 1]] = m1[[1, 0]]
m1

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
m1[[3, 2]] = m1[[2, 3]]
m1

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
m1.transpose() #m1.T

array([[ 4,  0,  8, 12],
       [ 5,  1,  9, 13],
       [ 6,  2, 10, 14],
       [ 7,  3, 11, 15]])

In [36]:
m2 = np.arange(0, 36).reshape(6,6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [38]:
m2[:, [0,1]] = m2[:, [1,0]]
m2

array([[ 1,  0,  2,  3,  4,  5],
       [ 7,  6,  8,  9, 10, 11],
       [13, 12, 14, 15, 16, 17],
       [19, 18, 20, 21, 22, 23],
       [25, 24, 26, 27, 28, 29],
       [31, 30, 32, 33, 34, 35]])

In [40]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[1,1], [1,1]])
C = np.concatenate((A,B))
C

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [1, 1]])

In [41]:
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print(M)
print('\n')
print(M.transpose())
print('\n')
print(M.T)

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]


[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [42]:
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
print(np.linalg.det(M))

195.0


In [43]:
print(np.linalg.matrix_rank(M))

3


In [44]:
print(np.linalg.inv(M))

[[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


In [45]:
#Matrislerin kuvvetleri
M1 = np.array([[1,2], [4,5]])
M1

array([[1, 2],
       [4, 5]])

In [46]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [47]:
np.linalg.matrix_power(M1, 3)

array([[ 57,  78],
       [156, 213]])

In [48]:
#TENSÖRLER

In [49]:
T1 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10, 20, 30], [40,50,60], [70,80,90]],
    [[100,200,300], [400, 500, 600], [700, 800, 900]],
])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [50]:
T2 = np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]]
])
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [51]:
A = T1 + T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [52]:
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [53]:
S = T1 - T2

In [54]:
S

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [56]:
np.subtract(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [57]:
P = T1*T2
P

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [58]:
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [59]:
D = T1 / T2
D

<ipython-input-59-f9444d3a0924>:1: RuntimeWarning: divide by zero encountered in true_divide
  D = T1 / T2


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [60]:
np.divide(T1, T2)

<ipython-input-60-b885ab1f8362>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(T1, T2)


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [61]:
np.tensordot(T1, T2)

array([[  63,   63,   63],
       [ 630,  630,  630],
       [6300, 6300, 6300]])

In [62]:
#Denklem Çözme, AX = B

In [63]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
B = np.random.random((3, 1))
B

array([[0.98391132],
       [0.42766883],
       [0.57544544]])

In [66]:
X = np.dot(np.linalg.inv(A), B)
X

array([[ 2.21943405e+15],
       [-4.43886811e+15],
       [ 2.21943405e+15]])

In [67]:
X = np.matmul(np.linalg.inv(A), B)
X

array([[ 2.21943405e+15],
       [-4.43886811e+15],
       [ 2.21943405e+15]])

In [69]:
X = np.linalg.inv(A)@B
X

array([[ 2.21943405e+15],
       [-4.43886811e+15],
       [ 2.21943405e+15]])

In [70]:
X = np.linalg.solve(A, B)
X

array([[ 2.21943405e+15],
       [-4.43886811e+15],
       [ 2.21943405e+15]])

In [71]:
#PANDAS

In [72]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [73]:
#Seriler

In [74]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [75]:
s1.dtype

dtype('int32')

In [76]:
s1.nbytes

28

In [77]:
s1.shape

(7,)

In [78]:
len(s1)

7

In [79]:
#count, size

In [80]:
s0 = pd.Series([1,2,3], index = ['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [81]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [82]:
v2 = np.random.random(10)
ind2 = np.arange(10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.20173926, 0.40758409, 0.22562308, 0.58199316, 0.04075912,
        0.25333511, 0.29506941, 0.82728061, 0.17796693, 0.89435785]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.201739
 1    0.407584
 2    0.225623
 3    0.581993
 4    0.040759
 5    0.253335
 6    0.295069
 7    0.827281
 8    0.177967
 9    0.894358
 dtype: float64)

In [83]:
dict1 = {'a1' : 10, 'a2' : 20, 'a3' : 30, 'a4' : 40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [84]:
pd.Series(99, index = [0,1,2,3,4,5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [85]:
#Serileri Bölme (Slicing)

In [86]:
s

0    0.201739
1    0.407584
2    0.225623
3    0.581993
4    0.040759
5    0.253335
6    0.295069
7    0.827281
8    0.177967
9    0.894358
dtype: float64

In [87]:
s[:]

0    0.201739
1    0.407584
2    0.225623
3    0.581993
4    0.040759
5    0.253335
6    0.295069
7    0.827281
8    0.177967
9    0.894358
dtype: float64

In [89]:
s[0:3]

0    0.201739
1    0.407584
2    0.225623
dtype: float64

In [90]:
s[-1:]

9    0.894358
dtype: float64

In [91]:
s[:4]

0    0.201739
1    0.407584
2    0.225623
3    0.581993
dtype: float64

In [92]:
s[-2:]

8    0.177967
9    0.894358
dtype: float64

In [93]:
s[-3:-1]

7    0.827281
8    0.177967
dtype: float64

In [94]:
#Serilerin Sonuna Eleman Ekleme (Append)

In [95]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [96]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [97]:
s4 = s2.append(s3)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [98]:
#Silme (drop)
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [99]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [100]:
s4.drop('a4', inplace = True)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [101]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [102]:
s4 = s4.append(pd.Series({'a4' : 7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [103]:
v1 = np.array([10, 20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1, s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [104]:
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [105]:
s1.sub(s2)

0     9
1    18
2    27
dtype: int32

In [106]:
s1.add(9)

0    19
1    29
2    39
dtype: int32

In [107]:
s1.mul(s2)

0    10
1    40
2    90
dtype: int32

In [108]:
s1.multiply(s2)

0    10
1    40
2    90
dtype: int32

In [109]:
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int32

In [110]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [111]:
s1.div(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [112]:
#s1.max(), min(), mean(), median(), std()

In [113]:
s1.equals(s2)

False

In [114]:
s5 = pd.Series([1,1,2,2,3,3], index=[0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [115]:
s5.value_counts()

1    2
2    2
3    2
dtype: int64