In [1]:
import numpy as np
import pandas as pd

dates = pd.date_range(start = '2023-02-13', periods = 7) 

M = np.random.random((7,7))

dframe = pd.DataFrame(M, index = dates)
dframe.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

C1        C2        C3        C4        C5        C6  \
2023-02-13  0.131509  0.355559  0.147444  0.168105  0.081583  0.829630   
2023-02-14  0.859793  0.189098  0.699724  0.293935  0.795075  0.001866   
2023-02-15  0.440680  0.738220  0.536372  0.420815  0.505966  0.004821   
2023-02-16  0.089416  0.128466  0.791211  0.424282  0.455101  0.186530   
2023-02-17  0.690195  0.144128  0.383238  0.151593  0.967014  0.825049   
2023-02-18  0.960027  0.031166  0.254481  0.593577  0.662807  0.106681   
2023-02-19  0.198614  0.712239  0.259394  0.031116  0.178877  0.410511   

                  C7  
2023-02-13  0.079388  
2023-02-14  0.224013  
2023-02-15  0.875531  
2023-02-16  0.914532  
2023-02-17  0.296829  
2023-02-18  0.035443  
2023-02-19  0.454033

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dframe['C1'] = 888
dframe.loc[0:3, 'C6'] = 777
dframe.iloc[0, 2] = 555
dframe.loc[0:5, 'C7'] = np.NaN
dframe.loc[0:2, 'C6'] = np.NaN
dframe.loc[5:6, 'C5'] = np.NaN
dframe

C1        C2          C3        C4        C5          C6  \
2023-02-13  888  0.355559  555.000000  0.168105  0.081583         NaN   
2023-02-14  888  0.189098    0.699724  0.293935  0.795075         NaN   
2023-02-15  888  0.738220    0.536372  0.420815  0.505966  777.000000   
2023-02-16  888  0.128466    0.791211  0.424282  0.455101    0.186530   
2023-02-17  888  0.144128    0.383238  0.151593  0.967014    0.825049   
2023-02-18  888  0.031166    0.254481  0.593577       NaN    0.106681   
2023-02-19  888  0.712239    0.259394  0.031116  0.178877    0.410511   

                  C7  
2023-02-13       NaN  
2023-02-14       NaN  
2023-02-15       NaN  
2023-02-16       NaN  
2023-02-17       NaN  
2023-02-18  0.035443  
2023-02-19  0.454033

In [4]:
dframe.fillna(value = {'C5': 123, 'C6':789})

C1        C2          C3        C4          C5          C6  \
2023-02-13  888  0.355559  555.000000  0.168105    0.081583  789.000000   
2023-02-14  888  0.189098    0.699724  0.293935    0.795075  789.000000   
2023-02-15  888  0.738220    0.536372  0.420815    0.505966  777.000000   
2023-02-16  888  0.128466    0.791211  0.424282    0.455101    0.186530   
2023-02-17  888  0.144128    0.383238  0.151593    0.967014    0.825049   
2023-02-18  888  0.031166    0.254481  0.593577  123.000000    0.106681   
2023-02-19  888  0.712239    0.259394  0.031116    0.178877    0.410511   

                  C7  
2023-02-13       NaN  
2023-02-14       NaN  
2023-02-15       NaN  
2023-02-16       NaN  
2023-02-17       NaN  
2023-02-18  0.035443  
2023-02-19  0.454033

In [5]:
dframe.fillna(value = {'C7' : 789}, limit = 1)

C1        C2          C3        C4        C5          C6  \
2023-02-13  888  0.355559  555.000000  0.168105  0.081583         NaN   
2023-02-14  888  0.189098    0.699724  0.293935  0.795075         NaN   
2023-02-15  888  0.738220    0.536372  0.420815  0.505966  777.000000   
2023-02-16  888  0.128466    0.791211  0.424282  0.455101    0.186530   
2023-02-17  888  0.144128    0.383238  0.151593  0.967014    0.825049   
2023-02-18  888  0.031166    0.254481  0.593577       NaN    0.106681   
2023-02-19  888  0.712239    0.259394  0.031116  0.178877    0.410511   

                    C7  
2023-02-13  789.000000  
2023-02-14         NaN  
2023-02-15         NaN  
2023-02-16         NaN  
2023-02-17         NaN  
2023-02-18    0.035443  
2023-02-19    0.454033

In [6]:
dframe.dropna()

C1        C2        C3        C4        C5        C6        C7
2023-02-19  888  0.712239  0.259394  0.031116  0.178877  0.410511  0.454033

In [7]:
dframe.dropna(axis = 'columns')

C1        C2          C3        C4
2023-02-13  888  0.355559  555.000000  0.168105
2023-02-14  888  0.189098    0.699724  0.293935
2023-02-15  888  0.738220    0.536372  0.420815
2023-02-16  888  0.128466    0.791211  0.424282
2023-02-17  888  0.144128    0.383238  0.151593
2023-02-18  888  0.031166    0.254481  0.593577
2023-02-19  888  0.712239    0.259394  0.031116

In [8]:
dframe

C1        C2          C3        C4        C5          C6  \
2023-02-13  888  0.355559  555.000000  0.168105  0.081583         NaN   
2023-02-14  888  0.189098    0.699724  0.293935  0.795075         NaN   
2023-02-15  888  0.738220    0.536372  0.420815  0.505966  777.000000   
2023-02-16  888  0.128466    0.791211  0.424282  0.455101    0.186530   
2023-02-17  888  0.144128    0.383238  0.151593  0.967014    0.825049   
2023-02-18  888  0.031166    0.254481  0.593577       NaN    0.106681   
2023-02-19  888  0.712239    0.259394  0.031116  0.178877    0.410511   

                  C7  
2023-02-13       NaN  
2023-02-14       NaN  
2023-02-15       NaN  
2023-02-16       NaN  
2023-02-17       NaN  
2023-02-18  0.035443  
2023-02-19  0.454033

In [9]:
dframe.dropna(subset = ['C5', 'C6'])

C1        C2        C3        C4        C5          C6        C7
2023-02-15  888  0.738220  0.536372  0.420815  0.505966  777.000000       NaN
2023-02-16  888  0.128466  0.791211  0.424282  0.455101    0.186530       NaN
2023-02-17  888  0.144128  0.383238  0.151593  0.967014    0.825049       NaN
2023-02-19  888  0.712239  0.259394  0.031116  0.178877    0.410511  0.454033

In [10]:
#Açıklayıcı İstatistikler (Descriptive Statistics)

In [11]:
dframe.fillna(55, inplace = True)
dframe

C1        C2          C3        C4         C5          C6  \
2023-02-13  888  0.355559  555.000000  0.168105   0.081583   55.000000   
2023-02-14  888  0.189098    0.699724  0.293935   0.795075   55.000000   
2023-02-15  888  0.738220    0.536372  0.420815   0.505966  777.000000   
2023-02-16  888  0.128466    0.791211  0.424282   0.455101    0.186530   
2023-02-17  888  0.144128    0.383238  0.151593   0.967014    0.825049   
2023-02-18  888  0.031166    0.254481  0.593577  55.000000    0.106681   
2023-02-19  888  0.712239    0.259394  0.031116   0.178877    0.410511   

                   C7  
2023-02-13  55.000000  
2023-02-14  55.000000  
2023-02-15  55.000000  
2023-02-16  55.000000  
2023-02-17  55.000000  
2023-02-18   0.035443  
2023-02-19   0.454033

In [12]:
dframe.mean()

C1    888.000000
C2      0.328411
C3     79.703489
C4      0.297632
C5      8.283374
C6    126.932681
C7     39.355639
dtype: float64

In [13]:
#max(), min(), median(), std(), var(), sum()

In [14]:
dframe.describe()

C1        C2          C3        C4         C5          C6         C7
count    7.0  7.000000    7.000000  7.000000   7.000000    7.000000   7.000000
mean   888.0  0.328411   79.703489  0.297632   8.283374  126.932681  39.355639
std      0.0  0.288012  209.586164  0.194913  20.602464  287.806809  26.718105
min    888.0  0.031166    0.254481  0.031116   0.081583    0.106681   0.035443
25%    888.0  0.136297    0.321316  0.159849   0.316989    0.298520  27.727017
50%    888.0  0.189098    0.536372  0.293935   0.505966    0.825049  55.000000
75%    888.0  0.533899    0.745467  0.422549   0.881044   55.000000  55.000000
max    888.0  0.738220  555.000000  0.593577  55.000000  777.000000  55.000000

In [15]:
import statistics as st
dframe.loc[3:6, 'C1'] = 22
dframe

C1        C2          C3        C4         C5          C6  \
2023-02-13  888  0.355559  555.000000  0.168105   0.081583   55.000000   
2023-02-14  888  0.189098    0.699724  0.293935   0.795075   55.000000   
2023-02-15  888  0.738220    0.536372  0.420815   0.505966  777.000000   
2023-02-16   22  0.128466    0.791211  0.424282   0.455101    0.186530   
2023-02-17   22  0.144128    0.383238  0.151593   0.967014    0.825049   
2023-02-18   22  0.031166    0.254481  0.593577  55.000000    0.106681   
2023-02-19  888  0.712239    0.259394  0.031116   0.178877    0.410511   

                   C7  
2023-02-13  55.000000  
2023-02-14  55.000000  
2023-02-15  55.000000  
2023-02-16  55.000000  
2023-02-17  55.000000  
2023-02-18   0.035443  
2023-02-19   0.454033

In [16]:
st.mean(dframe['C1'])

516.8571428571429

In [17]:
st.harmonic_mean(dframe['C1'])

49.69186046511628

In [18]:
arr = np.array([1,2,3,4,5,6,7,8])
st.median(arr)

4.5

In [19]:
st.median_low(arr)

4

In [20]:
st.median_high(arr)

5

In [21]:
#variance(), stdev()

In [22]:
#DF üzerine fonksiyon uygulama

In [23]:
dframe

C1        C2          C3        C4         C5          C6  \
2023-02-13  888  0.355559  555.000000  0.168105   0.081583   55.000000   
2023-02-14  888  0.189098    0.699724  0.293935   0.795075   55.000000   
2023-02-15  888  0.738220    0.536372  0.420815   0.505966  777.000000   
2023-02-16   22  0.128466    0.791211  0.424282   0.455101    0.186530   
2023-02-17   22  0.144128    0.383238  0.151593   0.967014    0.825049   
2023-02-18   22  0.031166    0.254481  0.593577  55.000000    0.106681   
2023-02-19  888  0.712239    0.259394  0.031116   0.178877    0.410511   

                   C7  
2023-02-13  55.000000  
2023-02-14  55.000000  
2023-02-15  55.000000  
2023-02-16  55.000000  
2023-02-17  55.000000  
2023-02-18   0.035443  
2023-02-19   0.454033

In [24]:
dframe.apply(max)

C1    888.000000
C2      0.738220
C3    555.000000
C4      0.593577
C5     55.000000
C6    777.000000
C7     55.000000
dtype: float64

In [25]:
dframe.apply(min)

C1    22.000000
C2     0.031166
C3     0.254481
C4     0.031116
C5     0.081583
C6     0.106681
C7     0.035443
dtype: float64

In [26]:
dframe.apply(sum)

C1    3618.000000
C2       2.298876
C3     557.924420
C4       2.083423
C5      57.983616
C6     888.528770
C7     275.489476
dtype: float64

In [27]:
dframe.apply(np.sum, axis = 1)

2023-02-13    1553.605246
2023-02-14     999.977832
2023-02-15    1722.201374
2023-02-16      78.985589
2023-02-17      79.471021
2023-02-18      78.021346
2023-02-19     890.046171
Freq: D, dtype: float64

In [28]:
dframe.applymap(np.sqrt)

C1        C2         C3        C4        C5         C6  \
2023-02-13  29.799329  0.596287  23.558438  0.410006  0.285628   7.416198   
2023-02-14  29.799329  0.434855   0.836495  0.542158  0.891670   7.416198   
2023-02-15  29.799329  0.859197   0.732374  0.648703  0.711313  27.874720   
2023-02-16   4.690416  0.358422   0.889500  0.651369  0.674612   0.431891   
2023-02-17   4.690416  0.379642   0.619062  0.389349  0.983369   0.908322   
2023-02-18   4.690416  0.176538   0.504461  0.770439  7.416198   0.326620   
2023-02-19  29.799329  0.843943   0.509307  0.176398  0.422939   0.640711   

                  C7  
2023-02-13  7.416198  
2023-02-14  7.416198  
2023-02-15  7.416198  
2023-02-16  7.416198  
2023-02-17  7.416198  
2023-02-18  0.188262  
2023-02-19  0.673820

In [29]:
import math
dframe.applymap(math.sqrt)

C1        C2         C3        C4        C5         C6  \
2023-02-13  29.799329  0.596287  23.558438  0.410006  0.285628   7.416198   
2023-02-14  29.799329  0.434855   0.836495  0.542158  0.891670   7.416198   
2023-02-15  29.799329  0.859197   0.732374  0.648703  0.711313  27.874720   
2023-02-16   4.690416  0.358422   0.889500  0.651369  0.674612   0.431891   
2023-02-17   4.690416  0.379642   0.619062  0.389349  0.983369   0.908322   
2023-02-18   4.690416  0.176538   0.504461  0.770439  7.416198   0.326620   
2023-02-19  29.799329  0.843943   0.509307  0.176398  0.422939   0.640711   

                  C7  
2023-02-13  7.416198  
2023-02-14  7.416198  
2023-02-15  7.416198  
2023-02-16  7.416198  
2023-02-17  7.416198  
2023-02-18  0.188262  
2023-02-19  0.673820

In [30]:
dframe.applymap(float)

C1        C2          C3        C4         C5          C6  \
2023-02-13  888.0  0.355559  555.000000  0.168105   0.081583   55.000000   
2023-02-14  888.0  0.189098    0.699724  0.293935   0.795075   55.000000   
2023-02-15  888.0  0.738220    0.536372  0.420815   0.505966  777.000000   
2023-02-16   22.0  0.128466    0.791211  0.424282   0.455101    0.186530   
2023-02-17   22.0  0.144128    0.383238  0.151593   0.967014    0.825049   
2023-02-18   22.0  0.031166    0.254481  0.593577  55.000000    0.106681   
2023-02-19  888.0  0.712239    0.259394  0.031116   0.178877    0.410511   

                   C7  
2023-02-13  55.000000  
2023-02-14  55.000000  
2023-02-15  55.000000  
2023-02-16  55.000000  
2023-02-17  55.000000  
2023-02-18   0.035443  
2023-02-19   0.454033

In [31]:
dframe.apply(lambda x : min(x))

C1    22.000000
C2     0.031166
C3     0.254481
C4     0.031116
C5     0.081583
C6     0.106681
C7     0.035443
dtype: float64

In [32]:
dframe.apply(lambda x : x*x)

C1        C2             C3        C4           C5  \
2023-02-13  788544  0.126422  308025.000000  0.028259     0.006656   
2023-02-14  788544  0.035758       0.489613  0.086398     0.632144   
2023-02-15  788544  0.544969       0.287695  0.177086     0.256001   
2023-02-16     484  0.016504       0.626015  0.180015     0.207117   
2023-02-17     484  0.020773       0.146871  0.022980     0.935116   
2023-02-18     484  0.000971       0.064760  0.352333  3025.000000   
2023-02-19  788544  0.507285       0.067285  0.000968     0.031997   

                       C6           C7  
2023-02-13    3025.000000  3025.000000  
2023-02-14    3025.000000  3025.000000  
2023-02-15  603729.000000  3025.000000  
2023-02-16       0.034793  3025.000000  
2023-02-17       0.680706  3025.000000  
2023-02-18       0.011381     0.001256  
2023-02-19       0.168519     0.206146

In [33]:
#DF birleştirme (merge)

In [34]:
daf1 = pd.DataFrame({'id' : ['1', '2', '3', '4', '5'], 'Name' : ['Ali İhsan', 'Betül', 'Fatoş', 'İsmail', 'Fırat']})
daf1

id       Name
0  1  Ali İhsan
1  2      Betül
2  3      Fatoş
3  4     İsmail
4  5      Fırat

In [35]:
daf2 = pd.DataFrame({'id' : ['1', '2', '6', '7', '8'], 'Score' : [40, 60, 80, 90, 70]})
daf2

id  Score
0  1     40
1  2     60
2  6     80
3  7     90
4  8     70

In [36]:
pd.merge(daf1, daf2, on = 'id', how = 'inner')

id       Name  Score
0  1  Ali İhsan     40
1  2      Betül     60

In [37]:
pd.merge(daf1, daf2, on = 'id', how = 'outer')

id       Name  Score
0  1  Ali İhsan   40.0
1  2      Betül   60.0
2  3      Fatoş    NaN
3  4     İsmail    NaN
4  5      Fırat    NaN
5  6        NaN   80.0
6  7        NaN   90.0
7  8        NaN   70.0

In [38]:
pd.merge(daf1, daf2, on = 'id', how = 'left')

id       Name  Score
0  1  Ali İhsan   40.0
1  2      Betül   60.0
2  3      Fatoş    NaN
3  4     İsmail    NaN
4  5      Fırat    NaN

In [39]:
pd.merge(daf1, daf2, on = 'id', how = 'right')

id       Name  Score
0  1  Ali İhsan     40
1  2      Betül     60
2  6        NaN     80
3  7        NaN     90
4  8        NaN     70

In [40]:
#DF'lerde dosya işlemleri

In [42]:
covid = pd.read_csv('mydata/covid19_1402.csv', delimiter = ',')
covid

FIPS  Admin2  Province_State        Country_Region          Last_Update  \
0     NaN     NaN             NaN           Afghanistan  2023-02-15 04:20:55   
1     NaN     NaN             NaN               Albania  2023-02-15 04:20:55   
2     NaN     NaN             NaN               Algeria  2023-02-15 04:20:55   
3     NaN     NaN             NaN               Andorra  2023-02-15 04:20:55   
4     NaN     NaN             NaN                Angola  2023-02-15 04:20:55   
...   ...     ...             ...                   ...                  ...   
4011  NaN     NaN             NaN    West Bank and Gaza  2023-02-15 04:20:55   
4012  NaN     NaN             NaN  Winter Olympics 2022  2023-02-15 04:20:55   
4013  NaN     NaN             NaN                 Yemen  2023-02-15 04:20:55   
4014  NaN     NaN             NaN                Zambia  2023-02-15 04:20:55   
4015  NaN     NaN             NaN              Zimbabwe  2023-02-15 04:20:55   

            Lat       Long_  Confirmed  Deaths  Recovered  Active  \
0     33.939110   67.709953   209036.0  7896.0        NaN     NaN   
1     41.153300   20.168300   334264.0  3596.0        NaN     NaN   
2     28.033900    1.659600   271409.0  6881.0        NaN     NaN   
3     42.506300    1.521800    47860.0   165.0        NaN     NaN   
4    -11.202700   17.873900   105184.0  1931.0        NaN     NaN   
...         ...         ...        ...     ...        ...     ...   
4011  31.952200   35.233200   703228.0  5708.0        NaN     NaN   
4012  39.904200  116.407400      535.0     0.0        NaN     NaN   
4013  15.552727   48.516388    11945.0  2159.0        NaN     NaN   
4014 -13.133897   27.849332   342317.0  4051.0        NaN     NaN   
4015 -19.015438   29.154857   263083.0  5659.0        NaN     NaN   

              Combined_Key  Incident_Rate  Case_Fatality_Ratio  
0              Afghanistan     536.976390             3.777340  
1                  Albania   11615.261658             1.075796  
2                  Algeria     618.933967             2.535288  
3                  Andorra   61942.664855             0.344756  
4                   Angola     320.036336             1.835831  
...                    ...            ...                  ...  
4011    West Bank and Gaza   13784.956961             0.811686  
4012  Winter Olympics 2022            NaN             0.000000  
4013                 Yemen      40.048994            18.074508  
4014                Zambia    1862.042098             1.183406  
4015              Zimbabwe    1770.061846             2.151032  

[4016 rows x 14 columns]

In [43]:
covid = covid.drop(['FIPS', 'Admin2', 'Province_State'], axis = 1)

In [44]:
covid

Country_Region          Last_Update        Lat       Long_  \
0              Afghanistan  2023-02-15 04:20:55  33.939110   67.709953   
1                  Albania  2023-02-15 04:20:55  41.153300   20.168300   
2                  Algeria  2023-02-15 04:20:55  28.033900    1.659600   
3                  Andorra  2023-02-15 04:20:55  42.506300    1.521800   
4                   Angola  2023-02-15 04:20:55 -11.202700   17.873900   
...                    ...                  ...        ...         ...   
4011    West Bank and Gaza  2023-02-15 04:20:55  31.952200   35.233200   
4012  Winter Olympics 2022  2023-02-15 04:20:55  39.904200  116.407400   
4013                 Yemen  2023-02-15 04:20:55  15.552727   48.516388   
4014                Zambia  2023-02-15 04:20:55 -13.133897   27.849332   
4015              Zimbabwe  2023-02-15 04:20:55 -19.015438   29.154857   

      Confirmed  Deaths  Recovered  Active          Combined_Key  \
0      209036.0  7896.0        NaN     NaN           Afghanistan   
1      334264.0  3596.0        NaN     NaN               Albania   
2      271409.0  6881.0        NaN     NaN               Algeria   
3       47860.0   165.0        NaN     NaN               Andorra   
4      105184.0  1931.0        NaN     NaN                Angola   
...         ...     ...        ...     ...                   ...   
4011   703228.0  5708.0        NaN     NaN    West Bank and Gaza   
4012      535.0     0.0        NaN     NaN  Winter Olympics 2022   
4013    11945.0  2159.0        NaN     NaN                 Yemen   
4014   342317.0  4051.0        NaN     NaN                Zambia   
4015   263083.0  5659.0        NaN     NaN              Zimbabwe   

      Incident_Rate  Case_Fatality_Ratio  
0        536.976390             3.777340  
1      11615.261658             1.075796  
2        618.933967             2.535288  
3      61942.664855             0.344756  
4        320.036336             1.835831  
...             ...                  ...  
4011   13784.956961             0.811686  
4012            NaN             0.000000  
4013      40.048994            18.074508  
4014    1862.042098             1.183406  
4015    1770.061846             2.151032  

[4016 rows x 11 columns]

In [45]:
covid = covid.drop(['Recovered', 'Active'], axis = 1)
covid

Country_Region          Last_Update        Lat       Long_  \
0              Afghanistan  2023-02-15 04:20:55  33.939110   67.709953   
1                  Albania  2023-02-15 04:20:55  41.153300   20.168300   
2                  Algeria  2023-02-15 04:20:55  28.033900    1.659600   
3                  Andorra  2023-02-15 04:20:55  42.506300    1.521800   
4                   Angola  2023-02-15 04:20:55 -11.202700   17.873900   
...                    ...                  ...        ...         ...   
4011    West Bank and Gaza  2023-02-15 04:20:55  31.952200   35.233200   
4012  Winter Olympics 2022  2023-02-15 04:20:55  39.904200  116.407400   
4013                 Yemen  2023-02-15 04:20:55  15.552727   48.516388   
4014                Zambia  2023-02-15 04:20:55 -13.133897   27.849332   
4015              Zimbabwe  2023-02-15 04:20:55 -19.015438   29.154857   

      Confirmed  Deaths          Combined_Key  Incident_Rate  \
0      209036.0  7896.0           Afghanistan     536.976390   
1      334264.0  3596.0               Albania   11615.261658   
2      271409.0  6881.0               Algeria     618.933967   
3       47860.0   165.0               Andorra   61942.664855   
4      105184.0  1931.0                Angola     320.036336   
...         ...     ...                   ...            ...   
4011   703228.0  5708.0    West Bank and Gaza   13784.956961   
4012      535.0     0.0  Winter Olympics 2022            NaN   
4013    11945.0  2159.0                 Yemen      40.048994   
4014   342317.0  4051.0                Zambia    1862.042098   
4015   263083.0  5659.0              Zimbabwe    1770.061846   

      Case_Fatality_Ratio  
0                3.777340  
1                1.075796  
2                2.535288  
3                0.344756  
4                1.835831  
...                   ...  
4011             0.811686  
4012             0.000000  
4013            18.074508  
4014             1.183406  
4015             2.151032  

[4016 rows x 9 columns]

In [46]:
covid.head(10)

Country_Region          Last_Update       Lat      Long_   Confirmed  \
0          Afghanistan  2023-02-15 04:20:55  33.93911  67.709953    209036.0   
1              Albania  2023-02-15 04:20:55  41.15330  20.168300    334264.0   
2              Algeria  2023-02-15 04:20:55  28.03390   1.659600    271409.0   
3              Andorra  2023-02-15 04:20:55  42.50630   1.521800     47860.0   
4               Angola  2023-02-15 04:20:55 -11.20270  17.873900    105184.0   
5           Antarctica  2023-02-15 04:20:55 -71.94990  23.347000        11.0   
6  Antigua and Barbuda  2023-02-15 04:20:55  17.06080 -61.796400      9106.0   
7            Argentina  2023-02-15 04:20:55 -38.41610 -63.616700  10042136.0   
8              Armenia  2023-02-15 04:20:55  40.06910  45.038200    446332.0   
9                  NaN                  NaN       NaN        NaN         NaN   

     Deaths         Combined_Key  Incident_Rate  Case_Fatality_Ratio  
0    7896.0          Afghanistan     536.976390             3.777340  
1    3596.0              Albania   11615.261658             1.075796  
2    6881.0              Algeria     618.933967             2.535288  
3     165.0              Andorra   61942.664855             0.344756  
4    1931.0               Angola     320.036336             1.835831  
5       0.0           Antarctica            NaN             0.000000  
6     146.0  Antigua and Barbuda    9298.668409             1.603338  
7  130448.0            Argentina   22219.190966             1.299007  
8    8719.0              Armenia   15062.327174             1.953479  
9       NaN                  NaN            NaN                  NaN

In [47]:
covid.head(5)

Country_Region          Last_Update       Lat      Long_  Confirmed  Deaths  \
0    Afghanistan  2023-02-15 04:20:55  33.93911  67.709953   209036.0  7896.0   
1        Albania  2023-02-15 04:20:55  41.15330  20.168300   334264.0  3596.0   
2        Algeria  2023-02-15 04:20:55  28.03390   1.659600   271409.0  6881.0   
3        Andorra  2023-02-15 04:20:55  42.50630   1.521800    47860.0   165.0   
4         Angola  2023-02-15 04:20:55 -11.20270  17.873900   105184.0  1931.0   

  Combined_Key  Incident_Rate  Case_Fatality_Ratio  
0  Afghanistan     536.976390             3.777340  
1      Albania   11615.261658             1.075796  
2      Algeria     618.933967             2.535288  
3      Andorra   61942.664855             0.344756  
4       Angola     320.036336             1.835831

In [48]:
covid.tail()

Country_Region          Last_Update        Lat       Long_  \
4011    West Bank and Gaza  2023-02-15 04:20:55  31.952200   35.233200   
4012  Winter Olympics 2022  2023-02-15 04:20:55  39.904200  116.407400   
4013                 Yemen  2023-02-15 04:20:55  15.552727   48.516388   
4014                Zambia  2023-02-15 04:20:55 -13.133897   27.849332   
4015              Zimbabwe  2023-02-15 04:20:55 -19.015438   29.154857   

      Confirmed  Deaths          Combined_Key  Incident_Rate  \
4011   703228.0  5708.0    West Bank and Gaza   13784.956961   
4012      535.0     0.0  Winter Olympics 2022            NaN   
4013    11945.0  2159.0                 Yemen      40.048994   
4014   342317.0  4051.0                Zambia    1862.042098   
4015   263083.0  5659.0              Zimbabwe    1770.061846   

      Case_Fatality_Ratio  
4011             0.811686  
4012             0.000000  
4013            18.074508  
4014             1.183406  
4015             2.151032

In [50]:
covid['Country_Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia', nan,
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Diamond Princess', 'Djibouti', 'Dominica', 'Dominican Republic',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Holy See', 'Honduras', '

In [51]:
covid['Country_Region'].nunique()

177

In [52]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4016 entries, 0 to 4015
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Country_Region       177 non-null    object 
 1   Last_Update          177 non-null    object 
 2   Lat                  175 non-null    float64
 3   Long_                175 non-null    float64
 4   Confirmed            177 non-null    float64
 5   Deaths               177 non-null    float64
 6   Combined_Key         177 non-null    object 
 7   Incident_Rate        172 non-null    float64
 8   Case_Fatality_Ratio  177 non-null    float64
dtypes: float64(6), object(3)
memory usage: 282.5+ KB


In [53]:
covid['Country_Region'].head(10)

0            Afghanistan
1                Albania
2                Algeria
3                Andorra
4                 Angola
5             Antarctica
6    Antigua and Barbuda
7              Argentina
8                Armenia
9                    NaN
Name: Country_Region, dtype: object

In [55]:
df1 = covid[['Country_Region', 'Confirmed', 'Deaths', 'Case_Fatality_Ratio']]
df1.head(10)

Country_Region   Confirmed    Deaths  Case_Fatality_Ratio
0          Afghanistan    209036.0    7896.0             3.777340
1              Albania    334264.0    3596.0             1.075796
2              Algeria    271409.0    6881.0             2.535288
3              Andorra     47860.0     165.0             0.344756
4               Angola    105184.0    1931.0             1.835831
5           Antarctica        11.0       0.0             0.000000
6  Antigua and Barbuda      9106.0     146.0             1.603338
7            Argentina  10042136.0  130448.0             1.299007
8              Armenia    446332.0    8719.0             1.953479
9                  NaN         NaN       NaN                  NaN

In [56]:
df1.iloc[1:4]

Country_Region  Confirmed  Deaths  Case_Fatality_Ratio
1        Albania   334264.0  3596.0             1.075796
2        Algeria   271409.0  6881.0             2.535288
3        Andorra    47860.0   165.0             0.344756

In [58]:
df1.loc[df1['Country_Region'] == 'Israel']

Country_Region  Confirmed   Deaths  Case_Fatality_Ratio
291         Israel  4792484.0  12242.0             0.255442

In [62]:
display('Sorted Data Frame', df1.sort_values(['Country_Region'], ascending = True).head(5))

'Sorted Data Frame'

Country_Region  Confirmed  Deaths  Case_Fatality_Ratio
0    Afghanistan   209036.0  7896.0             3.777340
1        Albania   334264.0  3596.0             1.075796
2        Algeria   271409.0  6881.0             2.535288
3        Andorra    47860.0   165.0             0.344756
4         Angola   105184.0  1931.0             1.835831

In [67]:
for index, row in df1.iterrows():
    if(row['Country_Region'] == 'Indonesia'):
        display(row[['Country_Region', 'Confirmed']])

Country_Region    Indonesia
Confirmed         6733215.0
Name: 287, dtype: object

In [69]:
covid['Country_Region'].drop_duplicates(keep = 'first').head(50)

0                   Afghanistan
1                       Albania
2                       Algeria
3                       Andorra
4                        Angola
5                    Antarctica
6           Antigua and Barbuda
7                     Argentina
8                       Armenia
9                           NaN
17                      Austria
18                   Azerbaijan
19                      Bahamas
20                      Bahrain
21                   Bangladesh
22                     Barbados
23                      Belarus
36                       Belize
37                        Benin
38                       Bhutan
39                      Bolivia
40       Bosnia and Herzegovina
41                     Botswana
69                       Brunei
70                     Bulgaria
71                 Burkina Faso
72                        Burma
73                      Burundi
74                   Cabo Verde
75                     Cambodia
76                     Cameroon
93     C

In [ ]:
#pokemon.csv

In [70]:
import scipy as sp

In [71]:
#scipy.linalg, scipy.special, scipy.integrate, scipy.optimize, scipy.fftpack
#scipy.signal, scipy.stats, scipy.ndimage, scipy.io

In [73]:
from scipy import linalg
A = np.array([[1,2], [3,4]])
print(A)
B = linalg.inv(A)
print(B)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [74]:
print(B.T)

[[-2.   1.5]
 [ 1.  -0.5]]


In [75]:
#Denklem takımının çözümü
A = np.array([[1,3,5], [2,5,1], [2,3,8]])
print(A)
b = np.array([[10], [8], [3]])
print(b)
print("Scipy ile yavaş çözüm")
print(linalg.inv(A).dot(b))
print("Numpy ile hızlı çözüm")
print(np.linalg.solve(A, b))

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[10]
 [ 8]
 [ 3]]
Scipy ile yavaş çözüm
[[-9.28]
 [ 5.16]
 [ 0.76]]
Numpy ile hızlı çözüm
[[-9.28]
 [ 5.16]
 [ 0.76]]


In [76]:
#İntegral
from scipy import integrate
x2 = lambda x : x ** 2
I = integrate.quad(x2, 0, 6)
print(I)

(72.00000000000001, 7.993605777301129e-13)


In [77]:
import scipy.integrate as integrate
import scipy.special as special

result = integrate.quad(lambda x : special.jv(2.5, x), 0, 4.5)
print(result)

(1.1178179380783244, 7.866317216380707e-09)


In [78]:
#Türev
from scipy.misc import derivative
def f(x):
    return x ** 3 + x ** 2
D = derivative(f, 1.0, dx = 1e-6)
print(D)

4.999999999921734


In [79]:
#Matrisleri çarpanlarına ayırma (LU Decomposition) -> A = L * U
from scipy.linalg import lu
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)
#LU çarpanlara ayırma
P, L, U = lu(A)
print(P)
print(L)
print(U)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


In [80]:
B = P.dot(L).dot(U)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [82]:
import pprint
import scipy
import scipy.linalg 
A = scipy.array([[7,3,-1,2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]])
P, L, U = scipy.linalg.lu(A)

print("A:")
pprint.pprint(A)
print("P:")
pprint.pprint(P)
print("L:")
pprint.pprint(L)
print("U:")
pprint.pprint(U)

A:
array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
P:
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])
U:
array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])
